name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: pip install -r requirements/linting.txt -r requirements/pyproject.txt pre-commit

    - run: pre-commit run -a --verbose
      env:
        SKIP: no-commit-to-branch

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: pip install -r requirements/docs.txt -r requirements/pyproject.txt
    - run: pip install .

    - run: make docs

    - name: Store docs site
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs/_build/

  test:
    name: test py${{ matrix.python }} with redis:${{ matrix.redis }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
        redis: ['5']
        include:
          - python: '3.11'
            redis: '6'
            os: 'ubuntu'
          - python: '3.11'
            redis: '7'
            os: 'ubuntu'

    env:
      PYTHON: ${{ matrix.python }}
      OS: ${{ matrix.os }}
      ARQ_TEST_REDIS_VERSION: ${{ matrix.redis }}

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - run: pip install -r requirements/testing.txt -r requirements/pyproject.txt

    - run: make test

    - run: coverage xml

    - uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        env_vars: PYTHON,OS

  check:
    if: always()
    needs: [lint, docs, test]
    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}

  release:
    name: Release
    needs: [check]
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install
        run: pip install -U build

      - name: build
        run: python -m build

      - name: Upload wheel to PyPI
        if: env.PYPI_SSH_KEY
        run: |
          scp dist/*.whl automate-infra-1.adjust.com:~/pypi/wheels
